// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnlggkvqfyagnzvxqvhx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBubGdna3ZxZnlhZ256dnhxdmh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMDYwMDEsImV4cCI6MjA2NzY4MjAwMX0.urhFhKBeY_avCyk74oIqfHd6VReyaI2V3gvB5GmMP7A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});